### ISSUE TITLE
似乎还没上传nb插件库

### ISSUE THREAD

**Issue by Jerry-Z07** [zouXH-god/nonebot-plugin-ACGalaxy#1]
执行 nb plugin install nonebot-plugin-ACGalaxy
提示 包 nonebot-plugin-ACGalaxy 未找到.

**Comment by zouXH-god** [comment]
我试了一下，没什么问题，你要不再试试呢
![Screenshot_2024-09-10-00-39-53-979_com.sonelli.juicessh.jpg](https://github.com/user-attachments/assets/d106b8f6-5444-4202-85a8-24e37d76a4e3)

**Comment by Jerry-Z07** [comment]
现在可以了
